name: Deploy Node.js App with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SSH_HOST # Reference your environment name here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "SSH_HOST is set to: ${{ secrets.SSH_HOST }}"
          echo "SSH_USER is set to: ${{ secrets.SSH_USER }}"
          echo "SSH_KEY is set: ${{ secrets.SSH_KEY:+Yes}}"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Connected to server"
            cd /var/www/basit-backend
            git pull origin main
            npm install --force
            pm2 restart backend || pm2 start index.js --name "backend"
